//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxTaxiSlimClient.CxTaxiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleTypes", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.DataContract")]
    public enum RoleTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payout = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CxTaxiSlimClient.CxTaxiService.ResultOfLoginInfoxdEytY2q))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<CxTaxiSlimClient.CxTaxiService.ErrorTypes> ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSucssiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<CxTaxiSlimClient.CxTaxiService.ErrorTypes> ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSucssied {
            get {
                return this.IsSucssiedField;
            }
            set {
                if ((this.IsSucssiedField.Equals(value) != true)) {
                    this.IsSucssiedField = value;
                    this.RaisePropertyChanged("IsSucssied");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfClientInfoxdEytY2q", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultOfClientInfoxdEytY2q : CxTaxiSlimClient.CxTaxiService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CxTaxiSlimClient.CxTaxiService.ClientInfo DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CxTaxiSlimClient.CxTaxiService.ClientInfo Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfLoginInfoxdEytY2q", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultOfLoginInfoxdEytY2q : CxTaxiSlimClient.CxTaxiService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CxTaxiSlimClient.CxTaxiService.LoginInfo DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CxTaxiSlimClient.CxTaxiService.LoginInfo Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorTypes", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.DataContract")]
    public enum ErrorTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoesntLogined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotInitialize = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginOrPassIsWrong = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnkownError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.DataContract")]
    [System.SerializableAttribute()]
    public partial class LoginInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CxTaxiSlimClient.CxTaxiService.RoleTypes RoleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CxTaxiSlimClient.CxTaxiService.RoleTypes RoleType {
            get {
                return this.RoleTypeField;
            }
            set {
                if ((this.RoleTypeField.Equals(value) != true)) {
                    this.RoleTypeField = value;
                    this.RaisePropertyChanged("RoleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionGuid {
            get {
                return this.SessionGuidField;
            }
            set {
                if ((this.SessionGuidField.Equals(value) != true)) {
                    this.SessionGuidField = value;
                    this.RaisePropertyChanged("SessionGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.DataContract")]
    [System.SerializableAttribute()]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddrDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorporationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultDiscountCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DiscountCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntranceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MarkupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrdersCanceledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrdersCounterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrDescription {
            get {
                return this.AddrDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AddrDescriptionField, value) != true)) {
                    this.AddrDescriptionField = value;
                    this.RaisePropertyChanged("AddrDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apartment {
            get {
                return this.ApartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartmentField, value) != true)) {
                    this.ApartmentField = value;
                    this.RaisePropertyChanged("Apartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAccountNumber {
            get {
                return this.BillingAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAccountNumberField, value) != true)) {
                    this.BillingAccountNumberField = value;
                    this.RaisePropertyChanged("BillingAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorporationName {
            get {
                return this.CorporationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CorporationNameField, value) != true)) {
                    this.CorporationNameField = value;
                    this.RaisePropertyChanged("CorporationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultDiscountCardNumber {
            get {
                return this.DefaultDiscountCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultDiscountCardNumberField, value) != true)) {
                    this.DefaultDiscountCardNumberField = value;
                    this.RaisePropertyChanged("DefaultDiscountCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultLanguage {
            get {
                return this.DefaultLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultLanguageField, value) != true)) {
                    this.DefaultLanguageField = value;
                    this.RaisePropertyChanged("DefaultLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultServiceName {
            get {
                return this.DefaultServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultServiceNameField, value) != true)) {
                    this.DefaultServiceNameField = value;
                    this.RaisePropertyChanged("DefaultServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DiscountCards {
            get {
                return this.DiscountCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountCardsField, value) != true)) {
                    this.DiscountCardsField = value;
                    this.RaisePropertyChanged("DiscountCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Entrance {
            get {
                return this.EntranceField;
            }
            set {
                if ((object.ReferenceEquals(this.EntranceField, value) != true)) {
                    this.EntranceField = value;
                    this.RaisePropertyChanged("Entrance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Markups {
            get {
                return this.MarkupsField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkupsField, value) != true)) {
                    this.MarkupsField = value;
                    this.RaisePropertyChanged("Markups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrdersCanceled {
            get {
                return this.OrdersCanceledField;
            }
            set {
                if ((this.OrdersCanceledField.Equals(value) != true)) {
                    this.OrdersCanceledField = value;
                    this.RaisePropertyChanged("OrdersCanceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrdersCounter {
            get {
                return this.OrdersCounterField;
            }
            set {
                if ((this.OrdersCounterField.Equals(value) != true)) {
                    this.OrdersCounterField = value;
                    this.RaisePropertyChanged("OrdersCounter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMethod", Namespace="http://schemas.datacontract.org/2004/07/WCFPlugin.Contract")]
    public enum SendMethod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Call = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CxTaxiService.IClientBonusService")]
    public interface IClientBonusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/Login", ReplyAction="http://tempuri.org/IClientBonusService/LoginResponse")]
        CxTaxiSlimClient.CxTaxiService.ResultOfLoginInfoxdEytY2q Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string pass, CxTaxiSlimClient.CxTaxiService.RoleTypes roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/Login", ReplyAction="http://tempuri.org/IClientBonusService/LoginResponse")]
        System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfLoginInfoxdEytY2q> LoginAsync(string login, string pass, CxTaxiSlimClient.CxTaxiService.RoleTypes roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/Logout", ReplyAction="http://tempuri.org/IClientBonusService/LogoutResponse")]
        void Logout(CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/Logout", ReplyAction="http://tempuri.org/IClientBonusService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/GetClientByPhone", ReplyAction="http://tempuri.org/IClientBonusService/GetClientByPhoneResponse")]
        CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q GetClientByPhone(string phone, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/GetClientByPhone", ReplyAction="http://tempuri.org/IClientBonusService/GetClientByPhoneResponse")]
        System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> GetClientByPhoneAsync(string phone, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/CreateNewClient", ReplyAction="http://tempuri.org/IClientBonusService/CreateNewClientResponse")]
        CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q CreateNewClient(string phone, string name, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/CreateNewClient", ReplyAction="http://tempuri.org/IClientBonusService/CreateNewClientResponse")]
        System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> CreateNewClientAsync(string phone, string name, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/PayoutFromAccount", ReplyAction="http://tempuri.org/IClientBonusService/PayoutFromAccountResponse")]
        CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q PayoutFromAccount(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/PayoutFromAccount", ReplyAction="http://tempuri.org/IClientBonusService/PayoutFromAccountResponse")]
        System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> PayoutFromAccountAsync(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/PayInToAccount", ReplyAction="http://tempuri.org/IClientBonusService/PayInToAccountResponse")]
        CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q PayInToAccount(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/PayInToAccount", ReplyAction="http://tempuri.org/IClientBonusService/PayInToAccountResponse")]
        System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> PayInToAccountAsync(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/SendPayinCode", ReplyAction="http://tempuri.org/IClientBonusService/SendPayinCodeResponse")]
        CxTaxiSlimClient.CxTaxiService.Result SendPayinCode(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/SendPayinCode", ReplyAction="http://tempuri.org/IClientBonusService/SendPayinCodeResponse")]
        System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.Result> SendPayinCodeAsync(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/SendPayoutCode", ReplyAction="http://tempuri.org/IClientBonusService/SendPayoutCodeResponse")]
        CxTaxiSlimClient.CxTaxiService.Result SendPayoutCode(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientBonusService/SendPayoutCode", ReplyAction="http://tempuri.org/IClientBonusService/SendPayoutCodeResponse")]
        System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.Result> SendPayoutCodeAsync(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientBonusServiceChannel : global::CxTaxiSlimClient.CxTaxiService.IClientBonusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientBonusServiceClient : System.ServiceModel.ClientBase<global::CxTaxiSlimClient.CxTaxiService.IClientBonusService>, global::CxTaxiSlimClient.CxTaxiService.IClientBonusService {
        
        public ClientBonusServiceClient() {
        }
        
        public ClientBonusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientBonusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientBonusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientBonusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CxTaxiSlimClient.CxTaxiService.ResultOfLoginInfoxdEytY2q Login(string login1, string pass, CxTaxiSlimClient.CxTaxiService.RoleTypes roleType) {
            return base.Channel.Login(login1, pass, roleType);
        }
        
        public System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfLoginInfoxdEytY2q> LoginAsync(string login, string pass, CxTaxiSlimClient.CxTaxiService.RoleTypes roleType) {
            return base.Channel.LoginAsync(login, pass, roleType);
        }
        
        public void Logout(CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            base.Channel.Logout(loginInfo);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.LogoutAsync(loginInfo);
        }
        
        public CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q GetClientByPhone(string phone, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.GetClientByPhone(phone, loginInfo);
        }
        
        public System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> GetClientByPhoneAsync(string phone, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.GetClientByPhoneAsync(phone, loginInfo);
        }
        
        public CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q CreateNewClient(string phone, string name, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.CreateNewClient(phone, name, loginInfo);
        }
        
        public System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> CreateNewClientAsync(string phone, string name, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.CreateNewClientAsync(phone, name, loginInfo);
        }
        
        public CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q PayoutFromAccount(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.PayoutFromAccount(clientId, operationCode, loginInfo);
        }
        
        public System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> PayoutFromAccountAsync(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.PayoutFromAccountAsync(clientId, operationCode, loginInfo);
        }
        
        public CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q PayInToAccount(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.PayInToAccount(clientId, operationCode, loginInfo);
        }
        
        public System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.ResultOfClientInfoxdEytY2q> PayInToAccountAsync(long clientId, int operationCode, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.PayInToAccountAsync(clientId, operationCode, loginInfo);
        }
        
        public CxTaxiSlimClient.CxTaxiService.Result SendPayinCode(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.SendPayinCode(clientId, phone, summ, sendMethod, loginInfo);
        }
        
        public System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.Result> SendPayinCodeAsync(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.SendPayinCodeAsync(clientId, phone, summ, sendMethod, loginInfo);
        }
        
        public CxTaxiSlimClient.CxTaxiService.Result SendPayoutCode(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.SendPayoutCode(clientId, phone, summ, sendMethod, loginInfo);
        }
        
        public System.Threading.Tasks.Task<CxTaxiSlimClient.CxTaxiService.Result> SendPayoutCodeAsync(long clientId, string phone, double summ, CxTaxiSlimClient.CxTaxiService.SendMethod sendMethod, CxTaxiSlimClient.CxTaxiService.LoginInfo loginInfo) {
            return base.Channel.SendPayoutCodeAsync(clientId, phone, summ, sendMethod, loginInfo);
        }
    }
}
