//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxTaxiSlimClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CxTaxiSlimClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить.
        /// </summary>
        internal static string BonusOperationsForm_btnOk_Do {
            get {
                return ResourceManager.GetString("BonusOperationsForm_btnOk_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        internal static string LoginForm_MessageCaption {
            get {
                return ResourceManager.GetString("LoginForm_MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя должно быть указано.
        /// </summary>
        internal static string LoginForm_UserNameCantBeEmpty {
            get {
                return ResourceManager.GetString("LoginForm_UserNameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string MainForm_Login {
            get {
                return ResourceManager.GetString("MainForm_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо войти в систему.
        /// </summary>
        internal static string MainForm_MustBeLogined {
            get {
                return ResourceManager.GetString("MainForm_MustBeLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не выполнен.
        /// </summary>
        internal static string MainForm_NotLogined {
            get {
                return ResourceManager.GetString("MainForm_NotLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона не должен быть пустым.
        /// </summary>
        internal static string MainForm_PhoneCantBeEmpty {
            get {
                return ResourceManager.GetString("MainForm_PhoneCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезайти.
        /// </summary>
        internal static string MainForm_Relogin {
            get {
                return ResourceManager.GetString("MainForm_Relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск клиента.
        /// </summary>
        internal static string MainForm_SearchClient {
            get {
                return ResourceManager.GetString("MainForm_SearchClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь: .
        /// </summary>
        internal static string MainForm_Title_User {
            get {
                return ResourceManager.GetString("MainForm_Title_User", resourceCulture);
            }
        }
    }
}
